config/routes.rb
Rails.application.routes.draw do
  root to: 'dates#index'
  get 'dates/index'

  resources :dates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, presence: true, length: {maximum: 20}
    validates :start, presence: true
    validates :end_date, presence: true
    validates :memo, length: {maximum: 500}

    
    validate :date_cannot_be_in_the_past

    def date_cannot_be_in_the_past
        if self.start != nil && self.end_date != nil
        errors.add(:end_date, "の日付を正しく記入してください") unless
        self.start < self.end_date 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dates_controller.rb
class DatesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :end_date, :check, :memo))
    if @schedule.save
      flash[:notice]= "予定を新規登録しました"
      redirect_to :dates
    else
      flash[:notice_error]="予定の新規登録に失敗しました"
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start, :end_date, :check, :memo))
      flash[:notice]="予定IDが「#{@schedule.id}」の情報を更新しました"
      redirect_to :dates
    else
      flash[:notice_error]="予定の更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dates_helper.rb
module DatesHelper
end

app/views/dates/edit.html.erb
<div class = "container container-new">
    <div class ="pageTitle">
        <h2 class = "pageTitleText">予定の編集</h2>
    </div>

    <% if flash[:notice_error] %>
        <p class = "notice-error"><%= flash[:notice_error] %> </p>
    <% end %>

    <div class = "container">
    <div class = "FormContainer row">
    <%= form_with model: @schedule , url: date_path , method: :patch do |f| %>
        <div class = "FormTitleWrapper col-12 mb">
            <%= f.label :title, "タイトル" , class: 'Form FormTitle required'%>
            <%= f.text_field :title %>
        </div>
        <div class = "FormDateWrapper row mb">
            <div class = "FormDate1 col-6">
            <%= f.label :start, "開始日" , class: 'Form FormStart required' %>
            <%= f.date_field :start , min: Time.zone.now %>
            </div>
            <div class = "FormDate2 col-6">
            <%= f.label :end_date, "終了日" , class: 'Form FormEnd required' %>
            <%= f.date_field :end_date , min: Time.zone.now %>
            </div>
        </div>
        <div class = "FormCheckWrapper col-12 mb">
            <%= f.check_box :check ,{},checked_value = "○" , unchecked_value = "" %>
            <%= f.label :check, "終日の場合はチェックを入れます" , class: 'Form FormCheck' %>
        </div>
        <div class = "FormMemoWrapper col-12 mb">
            <%= f.label :memo, "スケジュールメモ" , class: 'Form FormMemo' %>
            <%= f.text_area :memo %>
        </div>
        <div class = "FormButtonWrapper">
            <%= link_to "キャンセル" , dates_path, class: "btn btn-sm btn-light", method: :get %>
            <%= f.submit "編集を完了する" , class: "btn btn-primary" %>
        </div>
    <% end %>
    </div>
    </div>
    
</div>

app/views/dates/index.html.erb
<div class = "container">
    <div class ="pageTitle">
        <h2 class = "pageTitleText">予定一覧</h2>


        <div class = "pageTitleLink">
        <%= link_to new_date_path , method: :get, class: "btn btn-primary" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>  新規追加
        <% end %>
        </div>
        <% if false %>
        <%= button_to "新規追加", {controller: "dates", action: "new"}, {method: :get, class: "btn btn-primary" } %>
        <% end %>
    </div>

    <% if flash[:notice] %>
        <p class = "notice"><%= flash[:notice] %> </p>
    <% end %>

    <table class= "table table-bordered">
        <thead class = "table-light">
            <tr>
                <th>ID</th>
                <th>タイトル</th>
                <th>開始日</th>
                <th>終了日</th>
                <th>終日</th>
                <th>更新日時</th>
                <th>詳細</th>
                <th>編集</th>
                <th>削除</th>
            </tr>
        </thead>
        <tbody>
            <% @schedules.each do |schedule| %>
            <tr>
                <td><%= schedule.id %></td>
                <td><%= schedule.title %></td>
                <td><%= schedule.start.strftime("%Y/%m/%d")%></td>
                <% if false %>
                <td><%= schedule.start.to_s(:date_jp) %></td>
                <td><%= schedule.end_date.to_s(:date_jp) %></td>
                <% end %>
                <td><%= schedule.end_date.strftime("%Y/%m/%d") %></td>
                <td><%= schedule.check %></td>
                <td><%= schedule.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
                <td><%= link_to "詳細", date_path(schedule) %></td>
                <td><%= link_to "編集", edit_date_path(schedule) %></td>
                <td><%= link_to "削除", date_path(schedule) , method: :delete , data:{ confirm:"本当に削除しますか？"} %></td> 
            </tr>
            <% end %>
        </tbody>
    </table>
    <div class = "pageFooter bg-white">
        <div class = "FooterSum">
            <span>
                予定の合計<%= Schedule.count %>件
            </span>
        </div>
        <div class = "FooterToday">
            <span>
                本日の日付<%= Date.current.strftime('%Y/%m/%d') %>
            </span>
        </div>
    </div>
</div>

app/views/dates/new.html.erb
<div class = "container container-new">
    <div class ="pageTitle">
        <h4 class = "pageTitleText">予定の新規追加</h4>
    </div>

    <% if flash[:notice_error] %>
        <p class = "notice-error"><%= flash[:notice_error] %> </p>
    <% end %>

    <div class = "container">
    <div class = "FormContainer row">
    <%= form_with model: @schedule , url: dates_path do |f| %>
        <div class = "FormTitleWrapper col-12 mb">
            <%= f.label :title, "タイトル" , class: 'Form FormTitle required'%>
            <%= f.text_field :title , placeholder: "タイトル" %>
        </div>
        <div class = "FormDateWrapper row mb">
            <div class = "FormDate1 col-6">
                <%= f.label :start, "開始日" , class: 'Form FormStart required' %>
                <%= f.date_field :start , min: Time.zone.now %>
            </div>
            <div class = "FormDate2 col-6">
                <%= f.label :end_date, "終了日" , class: 'Form FormEnd required' %>
                <%= f.date_field :end_date , min: Time.zone.now %>
            </div>
        </div>
        <div class = "FormCheckWrapper col-12 mb">
            <%= f.check_box :check ,{},checked_value = "○" , unchecked_value = "" %>
            <%= f.label :check, "終日の場合はチェックを入れます" , class: 'Form FormCheck' %>
        </div>
        <div class = "FormMemoWrapper col-12 mb">
            <%= f.label :memo, "スケジュールメモ" , class: 'Form FormMemo' %>
            <%= f.text_area :memo , placeholder: "スケジュールメモ 500字以内"%>
        </div>
        <div class = "FormButtonWrapper">
            <%= link_to "キャンセル" , dates_path, class: "btn btn-sm btn-light", method: :get %>
            <%= f.submit "保存" , class: "btn btn-primary" %>
        </div>
    <% end %>
    </div>
    </div>
    
</div>

app/views/dates/show.html.erb
<div class = "container container-new mb">
  <%= link_to "← 一覧に戻る", :dates %>
</div>

<div class = "container container-new">
  <div class = "pageTitle mb">
    <h3><%= @schedule.title %></h3>
    <%= button_to "編集", {controller: "dates", action: "edit"}, {method: :get ,class: "btn btn-primary"} %>
  </div>
  <div class = "showTable">
    <table class = "table table-bordered">
      <tr>
        <th>開始日</th>
        <td><%= @schedule.start %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @schedule.end_date %></td>
      </tr>
      <tr>
        <th>終日</th>
        <td><%= @schedule.check %></td>
      </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td><%= @schedule.memo %></td>
      </tr>
    </table>
    </div>
</div class = "container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar">
    <div class="container">
      <h5>スケジュール管理アプリ</h5>
    </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>